services:
  postgres:
    container_name: 'library-api-medium-db'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=library'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
